import type {Metadata} from "next"
import "./globals.css"
import localfont from "next/font/local"
import Menu from "@/components/menu"
import {Schoolbell} from "next/font/google"

const schoolbell = Schoolbell({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-schoolbell",
})

const clashDisplay = localfont({
  src: "/clashdisplay.otf",
  variable: "--font-clash-display",
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${clashDisplay.className} ${schoolbell.variable} antialiased`}>
        <Menu />
        {children}
      </body>
    </html>
  )
}
